<?php
defined( 'ABSPATH' ) || exit;

add_action( 'wp_enqueue_scripts', function () {

	// get_template_directory_uri() always resolves to this theme's directory,
	// whether active standalone or as a parent theme. get_stylesheet_uri()
	// must NOT be used here — when a child theme is active, it resolves to
	// the child's style.css, so the starter's CSS would never load.
	wp_enqueue_style(
		'gwill-style',
		get_template_directory_uri() . '/style.css',
		[],
		wp_get_theme( get_template() )->get( 'Version' )
	);

	// strategy => 'defer': the nav toggle JS is non-critical — it can load
	// after the document parses with zero visual penalty. The $args array
	// replaces the deprecated boolean 5th argument (removed in WP 6.3+).
	wp_enqueue_script(
		'gwill-main',
		get_template_directory_uri() . '/assets/js/main.js',
		[],
		wp_get_theme( get_template() )->get( 'Version' ),
		[ 'in_footer' => true, 'strategy' => 'defer' ]
	);

	// Required for threaded (nested) comment reply links to work.
	if ( is_singular() && comments_open() && get_option( 'thread_comments' ) ) {
		wp_enqueue_script( 'comment-reply' );
	}

	// ── Contact form scripts ──────────────────────────────────────────────────
	//
	// Registered here, enqueued on-demand by individual template parts:
	//   wp_enqueue_script( 'gwill-forms' );           — in every form partial
	//   wp_enqueue_script( 'gwill-forms-multistep' ); — in contact-multistep.php
	//   wp_enqueue_script( 'gwill-forms-exit' );      — in contact-exit-intent.php
	//
	// Scripts enqueued from within a template partial (after wp_head()) still
	// output correctly via wp_footer() when registered with in_footer => true.

	$ver = wp_get_theme( get_template() )->get( 'Version' );

	wp_register_script(
		'gwill-forms',
		get_template_directory_uri() . '/assets/js/forms.js',
		[],
		$ver,
		[ 'in_footer' => true, 'strategy' => 'defer' ]
	);

	// GwillForms.ajaxUrl is the only value forms.js needs from PHP.
	// wp_localize_script() outputs the inline <script> block only when
	// 'gwill-forms' is actually enqueued — no wasted bytes on other pages.
	//
	// wp_make_link_relative() strips scheme + domain → '/wp-admin/admin-ajax.php'.
	// The browser resolves it against the current origin, so AJAX works on any
	// domain: production, staging, or a dev tunnel (e.g. qzz.io, ngrok, Cloudflare).
	// Using admin_url() directly causes cross-origin failures when the WP siteurl
	// differs from the URL in the browser's address bar.
	wp_localize_script(
		'gwill-forms',
		'GwillForms',
		[
			'ajaxUrl'  => wp_make_link_relative( admin_url( 'admin-ajax.php' ) ),
			// Pre-baked nonce — logged-in users only. A logged-in user's page is
			// NEVER served from LiteSpeed's full-page cache (every cache plugin
			// skips caching for authenticated requests by default), so a nonce
			// baked directly into THIS page's HTML is guaranteed fresh — it was
			// generated by THIS exact PHP request, not pulled from a cached copy.
			// forms.js checks this first and skips the network round-trip to
			// nonceUrl entirely when it's present. Anonymous visitors get '' here
			// deliberately: their pages CAN be cached for hours, so baking a
			// nonce into that HTML would go stale long before the cache expires —
			// exactly the failure mode the separate nonceUrl fetch exists to avoid.
			'nonce'    => is_user_logged_in() ? wp_create_nonce( 'gwill_contact_form' ) : '',
			// Nonce endpoint — switched from REST API to admin-ajax.php in v1.0.46.
			// admin-ajax.php is excluded from LiteSpeed Cache by default so nonces
			// are always fresh. It also avoids rest_cookie_check_errors (priority 100)
			// which returned 403 for logged-in users hitting the REST endpoint without
			// an X-WP-Nonce header — the root cause of "Network error" on all forms.
			// Only reached now when 'nonce' above is empty (anonymous visitors).
			// Response shape: { "nonce": "..." } — identical to the old REST endpoint,
			// so forms.js needed no structural changes, only the new pre-bake check.
			'nonceUrl' => wp_make_link_relative( add_query_arg( 'action', 'gwill_get_nonce', admin_url( 'admin-ajax.php' ) ) ),
		]
	);

	wp_register_script(
		'gwill-forms-multistep',
		get_template_directory_uri() . '/assets/js/form-multistep.js',
		[ 'gwill-forms' ],   // guarantees forms.js executes first
		$ver,
		[ 'in_footer' => true, 'strategy' => 'defer' ]
	);

	// i18n strings for step counter ("Step 1 of 3") and required-field
	// validation ("Email is required."). Data is attached to the registered
	// handle and only output by WP when the handle is actually enqueued —
	// no wasted bytes on pages without the multistep form.
	wp_localize_script(
		'gwill-forms-multistep',
		'GwillMultistep',
		[
			'i18n' => [
				'step'       => __( 'Step', 'gwill-starter' ),
				'of'         => __( 'of', 'gwill-starter' ),
				'isRequired' => __( 'is required.', 'gwill-starter' ),
			],
		]
	);

	wp_register_script(
		'gwill-forms-exit',
		get_template_directory_uri() . '/assets/js/form-exit-intent.js',
		[ 'gwill-forms' ],
		$ver,
		[ 'in_footer' => true, 'strategy' => 'defer' ]
	);

	// ── Search scripts + styles ───────────────────────────────────────────────
	//
	// Both search scripts are registered here, enqueued on-demand by their
	// respective template parts (search-form-expandable.php calls gwill-search-expand;
	// search-form-modal.php calls gwill-search-modal). The CSS is shared and
	// registered once — each partial calls wp_enqueue_style( 'gwill-search' ).
	//
	// Combo A — Expandable (default, no external dependencies)
	wp_register_script(
		'gwill-search-expand',
		get_template_directory_uri() . '/assets/js/search-expandable.js',
		[],
		$ver,
		[ 'in_footer' => true, 'strategy' => 'defer' ]
	);

	// i18n strings for aria-labels set dynamically by search-expandable.js.
	wp_localize_script(
		'gwill-search-expand',
		'GwillExpand',
		[
			'i18n' => [
				'openSearch'  => __( 'Open search',  'gwill-starter' ),
				'closeSearch' => __( 'Close search', 'gwill-starter' ),
			],
		]
	);

	// Combo B — Modal + live search (opt-in, needs REST API)
	wp_register_script(
		'gwill-search-modal',
		get_template_directory_uri() . '/assets/js/search-modal.js',
		[],
		$ver,
		[ 'in_footer' => true, 'strategy' => 'defer' ]
	);

	// wp_make_link_relative() keeps the REST URL domain-agnostic for the same
	// reason as ajaxUrl — staging / tunnel domains resolve correctly.
	wp_localize_script(
		'gwill-search-modal',
		'GwillSearch',
		[
			'restUrl' => wp_make_link_relative( rest_url( 'gwill/v1/search' ) ),
			// homeUrl + the '?s=' query var is how search-modal.js builds the
			// "View all results" link. Deliberately NOT derived client-side from
			// window.location.origin — that gives only the protocol + domain,
			// dropping the path entirely on any WordPress install running in a
			// subdirectory (e.g. example.com/blog/), which would send "view all"
			// to example.com/?s=term instead of example.com/blog/?s=term. home_url()
			// is the only thing that knows the real site path.
			'homeUrl' => home_url( '/' ),
			'i18n'    => [
				'loading'   => __( 'Searching\u2026',                              'gwill-starter' ),
				'noResults' => __( 'No results found.',                            'gwill-starter' ),
				'error'     => __( 'Search unavailable. Press Enter to search.',   'gwill-starter' ),
				'viewAll'   => __( 'View all results \u2192',                      'gwill-starter' ),
			],
		]
	);

	// Shared CSS for all search components (expandable + modal + results page).
	wp_register_style(
		'gwill-search',
		get_template_directory_uri() . '/assets/css/search.css',
		[ 'gwill-style' ],
		$ver
	);

	// ── Dark mode ─────────────────────────────────────────────────────────────
	//
	// CSS is globally enqueued — the toggle lives in every page header, and
	// the [data-theme] token overrides must be present before any content renders.
	//
	// JS is registered here; enqueued on-demand by template-parts/ui/darkmode-toggle.php.
	// The flash-prevention inline script is output by gwill_darkmode_head_script()
	// in header.php, before wp_head() — see inc/darkmode.php.

	wp_enqueue_style(
		'gwill-darkmode',
		get_template_directory_uri() . '/assets/css/darkmode.css',
		[ 'gwill-style' ],
		$ver
	);

	wp_register_script(
		'gwill-darkmode',
		get_template_directory_uri() . '/assets/js/darkmode.js',
		[],
		$ver,
		// NOTE: No 'strategy' => 'defer' here. The flash-prevention script in
		// the <head> sets data-theme immediately (inc/darkmode.php). This script
		// only needs to: (a) attach the toggle click handler, (b) sync ARIA state,
		// (c) listen for OS preference changes. All three must happen without
		// user interaction. Chrome on Android can delay deferred scripts until
		// first interaction (scroll, tap) — that is the exact bug: device-system
		// dark shows until the user scrolls, because the localStorage preference
		// is applied by this deferred script. Removing defer ensures the script
		// runs synchronously at end of <body>, reliably, on every page load.
		[ 'in_footer' => true ]
	);

	// i18n strings for the toggle button aria-label (JS updates it on interaction).
	wp_localize_script(
		'gwill-darkmode',
		'GwillDarkmode',
		[
			'i18n' => [
				'switchToDark'  => __( 'Switch to dark mode',  'gwill-starter' ),
				'switchToLight' => __( 'Switch to light mode', 'gwill-starter' ),
			],
		]
	);

	// ── Vibe Comments dark mode (conditional) ────────────────────────────────
	//
	// Registered always so child themes can enqueue it manually if needed.
	// Auto-enqueued only when the Vibe Comments plugin is active — no wasted
	// HTTP request on builds that don't use it.
	//
	// If you swap comment plugins, register/enqueue that plugin's dark mode
	// stylesheet in the same pattern here. Always keep default WP comment
	// styles in darkmode.css; per-plugin overrides go in their own file.

	wp_register_style(
		'gwill-darkmode-vibe',
		get_template_directory_uri() . '/assets/css/darkmode-vibe-comments.css',
		[ 'gwill-darkmode' ],
		$ver
	);

	if ( in_array( 'vibe-comments/vibe-comments.php', (array) get_option( 'active_plugins', [] ), true ) ) {
		wp_enqueue_style( 'gwill-darkmode-vibe' );
	}

} );

// ── Customizer live preview ───────────────────────────────────────────────────

/**
 * Enqueue the Customizer postMessage handler inside the preview iframe only.
 *
 * customize_preview_init fires exclusively inside the Customizer preview
 * context — never on the public frontend. The 'customize-preview' dependency
 * ensures wp.customize is available before this script runs.
 *
 * @see inc/customizer.php  (settings using transport: 'postMessage')
 * @see assets/js/customizer-preview.js
 */
add_action( 'customize_preview_init', function () {
	wp_enqueue_script(
		'gwill-customizer-preview',
		get_template_directory_uri() . '/assets/js/customizer-preview.js',
		[ 'customize-preview' ],
		wp_get_theme( get_template() )->get( 'Version' ),
		[ 'in_footer' => true, 'strategy' => 'defer' ]
	);
} );
